export const COUNTRY_OPTIONS = [
  { code: 'KR', name: '韓國', timezone: 'Asia/Seoul', currencyCode: 'KRW', currencySymbol: '₩' },
  { code: 'JP', name: '日本', timezone: 'Asia/Tokyo', currencyCode: 'JPY', currencySymbol: '¥' },
  { code: 'TW', name: '台灣', timezone: 'Asia/Taipei', currencyCode: 'TWD', currencySymbol: 'NT$' },
  { code: 'TH', name: '泰國', timezone: 'Asia/Bangkok', currencyCode: 'THB', currencySymbol: '฿' },
  { code: 'VN', name: '越南', timezone: 'Asia/Ho_Chi_Minh', currencyCode: 'VND', currencySymbol: '₫' },
  { code: 'SG', name: '新加坡', timezone: 'Asia/Singapore', currencyCode: 'SGD', currencySymbol: 'S$' },
  { code: 'MY', name: '馬來西亞', timezone: 'Asia/Kuala_Lumpur', currencyCode: 'MYR', currencySymbol: 'RM' },
  { code: 'HK', name: '香港', timezone: 'Asia/Hong_Kong', currencyCode: 'HKD', currencySymbol: 'HK$' },
  { code: 'CN', name: '中國', timezone: 'Asia/Shanghai', currencyCode: 'CNY', currencySymbol: '¥' },
  { code: 'US', name: '美國', timezone: 'America/New_York', currencyCode: 'USD', currencySymbol: '$' },
  { code: 'AU', name: '澳洲', timezone: 'Australia/Sydney', currencyCode: 'AUD', currencySymbol: 'A$' },
  { code: 'NZ', name: '紐西蘭', timezone: 'Pacific/Auckland', currencyCode: 'NZD', currencySymbol: 'NZ$' },
  { code: 'GB', name: '英國', timezone: 'Europe/London', currencyCode: 'GBP', currencySymbol: '£' },
  { code: 'FR', name: '法國', timezone: 'Europe/Paris', currencyCode: 'EUR', currencySymbol: '€' },
  { code: 'IT', name: '義大利', timezone: 'Europe/Rome', currencyCode: 'EUR', currencySymbol: '€' },
  { code: 'DE', name: '德國', timezone: 'Europe/Berlin', currencyCode: 'EUR', currencySymbol: '€' },
];

export const WEATHER_CITY_OPTIONS = [
  { countryCode: 'KR', name: 'Seoul', label: '首爾', latitude: 37.5665, longitude: 126.978 },
  { countryCode: 'KR', name: 'Incheon', label: '仁川', latitude: 37.4563, longitude: 126.7052 },
  { countryCode: 'KR', name: 'Suwon', label: '水原', latitude: 37.2636, longitude: 127.0286 },
  { countryCode: 'KR', name: 'Chuncheon', label: '春川', latitude: 37.8813, longitude: 127.7298 },
  { countryCode: 'KR', name: 'Gangneung', label: '江陵', latitude: 37.7519, longitude: 128.8761 },
  { countryCode: 'KR', name: 'Daejeon', label: '大田', latitude: 36.3504, longitude: 127.3845 },
  { countryCode: 'KR', name: 'Daegu', label: '大邱', latitude: 35.8714, longitude: 128.6014 },
  { countryCode: 'KR', name: 'Gyeongju', label: '慶州', latitude: 35.8562, longitude: 129.2247 },
  { countryCode: 'KR', name: 'Busan', label: '釜山', latitude: 35.1796, longitude: 129.0756 },
  { countryCode: 'KR', name: 'Jeonju', label: '全州', latitude: 35.8242, longitude: 127.148 },
  { countryCode: 'KR', name: 'Gwangju', label: '光州', latitude: 35.1595, longitude: 126.8526 },
  { countryCode: 'KR', name: 'Yeosu', label: '麗水', latitude: 34.7604, longitude: 127.6622 },
  { countryCode: 'KR', name: 'Jeju-si', label: '濟州市', latitude: 33.5097, longitude: 126.5219 },
  { countryCode: 'KR', name: 'Seogwipo', label: '西歸浦', latitude: 33.2539, longitude: 126.5598 },
  { countryCode: 'JP', name: 'Sapporo', label: '札幌', latitude: 43.0642, longitude: 141.3469 },
  { countryCode: 'JP', name: 'Otaru', label: '小樽', latitude: 43.1907, longitude: 140.9947 },
  { countryCode: 'JP', name: 'Niseko', label: '二世谷', latitude: 42.8048, longitude: 140.6874 },
  { countryCode: 'JP', name: 'Furano', label: '富良野', latitude: 43.342, longitude: 142.3832 },
  { countryCode: 'JP', name: 'Biei', label: '美瑛', latitude: 43.5883, longitude: 142.4669 },
  { countryCode: 'JP', name: 'Asahikawa', label: '旭川', latitude: 43.7706, longitude: 142.365 },
  { countryCode: 'JP', name: 'Noboribetsu', label: '登別', latitude: 42.4128, longitude: 141.1066 },
  { countryCode: 'JP', name: 'Hakodate', label: '函館', latitude: 41.7687, longitude: 140.7291 },
  { countryCode: 'JP', name: 'Lake Toya', label: '洞爺湖', latitude: 42.5656, longitude: 140.8171 },
  { countryCode: 'JP', name: 'Abashiri', label: '網走', latitude: 44.0206, longitude: 144.2735 },
  { countryCode: 'JP', name: 'Kushiro', label: '釧路', latitude: 42.9849, longitude: 144.3818 },
  { countryCode: 'JP', name: 'Tokyo', label: '東京', latitude: 35.6762, longitude: 139.6503 },
  { countryCode: 'JP', name: 'Yokohama', label: '橫濱', latitude: 35.4437, longitude: 139.638 },
  { countryCode: 'JP', name: 'Kamakura', label: '鎌倉', latitude: 35.3192, longitude: 139.5467 },
  { countryCode: 'JP', name: 'Hakone', label: '箱根', latitude: 35.2324, longitude: 139.1069 },
  { countryCode: 'JP', name: 'Nagoya', label: '名古屋', latitude: 35.1815, longitude: 136.9066 },
  { countryCode: 'JP', name: 'Takayama', label: '高山', latitude: 36.1461, longitude: 137.2522 },
  { countryCode: 'JP', name: 'Kanazawa', label: '金澤', latitude: 36.5613, longitude: 136.6562 },
  { countryCode: 'JP', name: 'Kyoto', label: '京都', latitude: 35.0116, longitude: 135.7681 },
  { countryCode: 'JP', name: 'Osaka', label: '大阪', latitude: 34.6937, longitude: 135.5023 },
  { countryCode: 'JP', name: 'Nara', label: '奈良', latitude: 34.6851, longitude: 135.8048 },
  { countryCode: 'JP', name: 'Kobe', label: '神戶', latitude: 34.6901, longitude: 135.1955 },
  { countryCode: 'JP', name: 'Hiroshima', label: '廣島', latitude: 34.3853, longitude: 132.4553 },
  { countryCode: 'JP', name: 'Fukuoka', label: '福岡', latitude: 33.5902, longitude: 130.4017 },
  { countryCode: 'JP', name: 'Kumamoto', label: '熊本', latitude: 32.8031, longitude: 130.7079 },
  { countryCode: 'JP', name: 'Kagoshima', label: '鹿兒島', latitude: 31.5966, longitude: 130.5571 },
  { countryCode: 'JP', name: 'Naha', label: '那霸', latitude: 26.2124, longitude: 127.6809 },
  { countryCode: 'TW', name: 'Taipei', label: '台北', latitude: 25.033, longitude: 121.5654 },
  { countryCode: 'TW', name: 'Taichung', label: '台中', latitude: 24.1477, longitude: 120.6736 },
  { countryCode: 'TW', name: 'Tainan', label: '台南', latitude: 22.9999, longitude: 120.2269 },
  { countryCode: 'TW', name: 'Kaohsiung', label: '高雄', latitude: 22.6273, longitude: 120.3014 },
  { countryCode: 'TW', name: 'Hualien', label: '花蓮', latitude: 23.9872, longitude: 121.6015 },
  { countryCode: 'TH', name: 'Bangkok', label: '曼谷', latitude: 13.7563, longitude: 100.5018 },
  { countryCode: 'TH', name: 'Chiang Mai', label: '清邁', latitude: 18.7883, longitude: 98.9853 },
  { countryCode: 'TH', name: 'Phuket', label: '普吉島', latitude: 7.8804, longitude: 98.3923 },
  { countryCode: 'VN', name: 'Ho Chi Minh City', label: '胡志明市', latitude: 10.8231, longitude: 106.6297 },
  { countryCode: 'VN', name: 'Hanoi', label: '河內', latitude: 21.0278, longitude: 105.8342 },
  { countryCode: 'VN', name: 'Da Nang', label: '峴港', latitude: 16.0544, longitude: 108.2022 },
  { countryCode: 'SG', name: 'Singapore', label: '新加坡', latitude: 1.3521, longitude: 103.8198 },
  { countryCode: 'MY', name: 'Kuala Lumpur', label: '吉隆坡', latitude: 3.139, longitude: 101.6869 },
  { countryCode: 'HK', name: 'Hong Kong', label: '香港', latitude: 22.3193, longitude: 114.1694 },
  { countryCode: 'CN', name: 'Shanghai', label: '上海', latitude: 31.2304, longitude: 121.4737 },
  { countryCode: 'US', name: 'New York', label: '紐約', latitude: 40.7128, longitude: -74.006 },
  { countryCode: 'AU', name: 'Sydney', label: '雪梨', latitude: -33.8688, longitude: 151.2093 },
  { countryCode: 'NZ', name: 'Auckland', label: '奧克蘭', latitude: -36.8485, longitude: 174.7633 },
  { countryCode: 'GB', name: 'London', label: '倫敦', latitude: 51.5072, longitude: -0.1276 },
  { countryCode: 'FR', name: 'Paris', label: '巴黎', latitude: 48.8566, longitude: 2.3522 },
  { countryCode: 'IT', name: 'Rome', label: '羅馬', latitude: 41.9028, longitude: 12.4964 },
  { countryCode: 'DE', name: 'Berlin', label: '柏林', latitude: 52.52, longitude: 13.405 },
];

export const getCountryOption = (countryCode) =>
  COUNTRY_OPTIONS.find((item) => item.code === countryCode) || COUNTRY_OPTIONS[0];

export const getWeatherCitiesByCountry = (countryCode) =>
  WEATHER_CITY_OPTIONS.filter((item) => item.countryCode === countryCode);

export const getDefaultWeatherCity = (countryCode) =>
  getWeatherCitiesByCountry(countryCode)[0] || WEATHER_CITY_OPTIONS[0];
