/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminDataTable: typeof import('./components/admin/AdminDataTable.vue')['default']
    AdminDrawer: typeof import('./components/admin/AdminDrawer.vue')['default']
    AdminFormPanel: typeof import('./components/admin/AdminFormPanel.vue')['default']
    AdminItineraryItemForm: typeof import('./components/admin/AdminItineraryItemForm.vue')['default']
    AdminNavMenuItem: typeof import('./components/admin/AdminNavMenuItem.vue')['default']
    AdminTripSelector: typeof import('./components/AdminTripSelector.vue')['default']
    CurrencyConverter: typeof import('./components/CurrencyConverter.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    IOSInstallPrompt: typeof import('./components/IOSInstallPrompt.vue')['default']
    ItineraryCard: typeof import('./components/ItineraryCard.vue')['default']
    PackingList: typeof import('./components/PackingList.vue')['default']
    PayCard: typeof import('./components/PayCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WalletAnalysis: typeof import('./components/WalletAnalysis.vue')['default']
    WalletSettlement: typeof import('./components/WalletSettlement.vue')['default']
    WeatherCard: typeof import('./components/WeatherCard.vue')['default']
  }
}
